#!/usr/bin/env php
<?php
require_once __DIR__ . '/app/autoload.php';
/*
$m = new Mapper;
$m->init();*/
$params = '{"page":"1","where":"1=1","order":"by id asc","limit":"12"}';
extract( json_decode( $params, true ) );
pr( json_decode( $params, true ) );
pr( $page ); 
pr( $where ); 
pr( $order ); 
pr( $limit ); 